version: '3'
services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: rtsp_simulator
    ports:
      - "8554:8554"   # RTSP
      - "1935:1935"   # RTMP
      - "8888:8888"   # HLS
      - "8889:8889"   # WebRTC
    restart: unless-stopped
